version: "3.8"
services:
  postgres:
    env_file: .env
    image: gitea.simcop2387.info/simcop2387/postgres-perl-social
    build:
      context: ./postgresql/
      dockerfile: Dockerfile
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432
  gitea:
    image: gitea/gitea:1.17
    container_name: gitea
    env_file: .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - postgres
  keycloak:
    restart: unless-stopped
    env_file: .env
    command: start --db=postgres
    build:
      context: ./keycloak/
      dockerfile: Dockerfile
    image: gitea.simcop2387.info/simcop2387/keycloak-perl-social
    depends_on:
      - postgres
    ports:
      - 8443:8443
  gotosocial:
    env_file: .env
    image: gitea.simcop2387.info/simcop2387/gotosocial-perl-social
    build:
      context: ./gotosocial/
      dockerfile: Dockerfile
      args:
        - GTS_DB_TYPE=$GTS_DB_TYPE
        - GTS_DB_ADDRESS=$GTS_DB_ADDRESS
        - GTS_DB_PORT=$GTS_DB_PORT
        - GTS_DB_USER=$GTS_DB_USER
        - GTS_DB_PASSWORD=$GTS_DB_PASSWORD
        - GTS_DB_DATABASE=$GTS_DB_DATABASE
    container_name: gotosocial
    user: 1000:1000
    ports:
      - "8444:8443"
      #- "80:80"
    volumes:
      - ./volumes/gotosocial/data:/gotosocial/storage
    restart: unless-stopped
    depends_on:
      - postgres
  smtp:
  # TODO, full system for local admin stuff?
    image: takeyamajp/postfix
    ports: []
    volumes:
      - ./postfix/certs:/ssl_certs
      - ./postfix/dkim:/dkim_keys
    env_file: .env.postfix
  caddy:
    image: gitea.simcop2387.info/simcop2387/caddy-perl-social
    build:
      context: ./caddy/
      dockerfile: Dockerfile
    ports:
      # TODO make these right for deployment
      - 8443:443
      - 8080:80
    volumes:
      - ./caddy/config/:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/caddy/data:/data
    env_file: .env
