version: "3.8"
services:
  gitea:
    image: gitea/gitea:1.17
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
  keycloak:
    restart: unless-stopped
    build:
      context: ./keycloak/
      dockerfile: Dockerfile
    image: gitea.simcop2387.info/simcop2387/keycloak-perl-social
  postgres:
    build:
      context: ./postgresql/
      dockerfile: Dockerfile
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
  gotosocial:
    build:
      context: ./gotosocial/
      dockerfile: Dockerfile
    container_name: gotosocial
    user: 1000:1000
    ports:
      - "443:8080"
      #- "80:80"
    volumes:
      - ./volumes/gotosocial/data:/gotosocial/storage
    restart: "always"
