version: "3.8"
services:
  postgres:
    env_file: .env
    image: gitea.simcop2387.info/simcop2387/postgres-perl-social
    build:
      context: ./postgresql/
      dockerfile: Dockerfile
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432
  gitea:
    image: gitea/gitea:1.17
    env_file: .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - postgres
      - smtp
  keycloak:
    restart: unless-stopped
    env_file: .env
    command: start --db=postgres
    build:
      context: ./keycloak/
      dockerfile: Dockerfile
    image: gitea.simcop2387.info/simcop2387/keycloak-perl-social
    depends_on:
      - postgres
  smtp:
  # TODO, full system for local admin stuff?
    image: takeyamajp/postfix
    ports: []
    volumes:
      - ./postfix/certs:/ssl_certs
      - ./postfix/dkim:/dkim_keys
    env_file: .env.postfix
  caddy:
    image: gitea.simcop2387.info/simcop2387/caddy-perl-social
    build:
      context: ./caddy/
      dockerfile: Dockerfile
    ports:
      # TODO make these right for deployment
      - 8443:443
      - 8080:80
    volumes:
      - ./caddy/config/:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/caddy/data:/data
    restart: unless-stopped
    env_file: .env
    depends_on:
      - keycloak
      - friendica
      - gitea
  mariadb:
    image: mariadb:10
    restart: unless-stopped
    env_file: .env
  friendica:
    image: friendica:latest
    restart: unless-stopped
    volumes:
      - ./volumes/friendica:/var/www/html
    env_file: .env
    depends_on:
      - mariadb
      - redis
      - smtp
  redis:
    image: redis:7.0
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PW
    volumes: 
      - ./volumes/redis/:/data
    env_file: .env